##############################################################
## Packager Section
##############################################################
SET (CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
SET (CPACK_PACKAGE_DESCRIPTION_SUMMARY "a XHTML/HTML Debugger for Web Development")
SET (CPACK_PACKAGE_VERSION_MAJOR ${XHTMLDBG_VERSION_MAJOR})
SET (CPACK_PACKAGE_VERSION_MINOR ${XHTMLDBG_VERSION_MINOR})
SET (CPACK_PACKAGE_VERSION_PATCH "${XHTMLDBG_VERSION_RELEASE}${XHTMLDBG_PATCHLEVEL}")
SET (CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README")
SET (CPACK_PACKAGE_CONTACT "Juergen Heinemann (Undefined) http://www.hjcms.de")
SET (CPACK_PACKAGE_LICENSE "GPLv3 LGPLv2+")
SET (CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/src/icons/qtidy.png")

IF (Q_WS_MAC)
  ## SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST ${CMAKE_SOURCE_DIR}/Info.plist.template)
  SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES MACOSX_BUNDLE_GUI_IDENTIFIER "de.hjcms.xhtmldbg")
  SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES MACOSX_BUNDLE_BUNDLE_NAME "XHTML/HTML Debugger")
ENDIF (Q_WS_MAC)

CONFIGURE_FILE (xhtmldbg.spec.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/xhtmldbg.spec
)

INCLUDE (CPack)

##EOF
